### ISSUE TITLE
Importing vanilla css

### ISSUE THREAD

**Issue by smuemd** [static-dev/spike-css-standards#13]
Is it possible to import vanilla css into sss files when using spike css standards?
I would like to use normalize.css etc. but failed to load it.

Any suggestions?

**Comment by jescalan** [comment]
No you can't, [sugarss](https://github.com/postcss/sugarss) isn't compatible with normal css syntax. This issue discusses it a bit, might be a good place to start digging: https://github.com/postcss/sugarss/issues/39

Immediate suggestions:
- Turn off sugarss with `parser: false` as an option
- Load normalize as a separate file with a link tag
- Find and replace brackets in the normalize.css file and remove them to make it sugarss-compatible

This issue is not something we can fix in this plugin pack, as far as I know, and the people who could resolve it would be either the maintainers of sugarss or postcss-import, so I'm going to close the issue. However, I still very much welcome discussion here, I just like to keep issues open when there's a possibility they could be resolved within the repo's codebase!

**Comment by smuemd** [comment]
Thanks for the note.
Just turning sugarss off seems like the best option for now. Although I really like your standard stack...
